/**
 * Report Writer.
 *
 * Generates a validated report grounded strictly in supplied stats. The demo
 * renderer produces Markdown offline; live mode may rephrase but is validated.
 */

import {
  reportSchema,
  type ReportResult,
  type ReportType,
} from "@/lib/ai/schemas/report.schema";
import {
  REPORT_SYSTEM_PROMPT,
  REPORT_VERSION,
  buildReportUserMessage,
} from "@/lib/ai/prompts/report-writer.prompt";
import { buildReportContext } from "@/lib/ai/context-builders/buildReportContext";
import { serializeContext } from "@/lib/ai/context-builders/types";
import { runStructuredTask } from "@/lib/ai/providers/aiProvider";

const TITLES: Record<ReportType, string> = {
  operations: "Daily Operations Report",
  impact_summary: "Weekly Impact Summary",
  donor_report: "Donor-Friendly Impact Report",
  leadership_brief: "Leadership Brief",
  resource_shortage: "Resource Shortage Analysis",
};

export interface ReportInput {
  reportType: ReportType;
  periodLabel: string;
  orgName: string;
  stats: Record<string, number | string>;
}

export function demoReport(input: ReportInput): ReportResult {
  const { reportType, periodLabel, stats } = input;
  const lines: string[] = [];
  lines.push(`# ${TITLES[reportType]}`);
  lines.push(`_Period: ${periodLabel} · ${input.orgName}_`);
  lines.push("");
  lines.push("## Summary");
  lines.push(
    "This report is generated by AidBridge AI from live operational counts. Figures are grounded strictly in the data below; no specifics are fabricated.",
  );
  lines.push("");
  lines.push("## Key metrics");
  for (const [k, v] of Object.entries(stats)) {
    lines.push(`- **${humanizeKey(k)}:** ${v}`);
  }
  lines.push("");
  lines.push("## Recommendations");
  if (reportType === "resource_shortage") {
    lines.push("- Replenish resource types at or below the shortage threshold.");
    lines.push("- Prioritize delivery-capable partners for high-urgency cases.");
  } else if (reportType === "donor_report") {
    lines.push("- Thank donors and share concrete, privacy-safe impact stories.");
    lines.push("- Highlight the volunteer hours contributed this period.");
  } else {
    lines.push("- Clear the human-review queue before dispatch.");
    lines.push("- Balance volunteer workload against per-day task caps.");
  }
  lines.push("");
  lines.push(
    "> AidBridge AI supports human coordinators; it does not replace emergency services or professional advice.",
  );

  const highlights = Object.entries(stats)
    .slice(0, 3)
    .map(([k, v]) => `${humanizeKey(k)}: ${v}`);

  return {
    report_type: reportType,
    title: TITLES[reportType],
    content: lines.join("\n"),
    highlights,
    metrics: stats,
    confidence_score: 0.9,
  };
}

function humanizeKey(k: string): string {
  return k.replace(/_/g, " ").replace(/^./, (c) => c.toUpperCase());
}

export async function writeReport(input: ReportInput) {
  const context = buildReportContext({
    reportType: input.reportType,
    periodLabel: input.periodLabel,
    stats: input.stats,
    orgName: input.orgName,
  });

  return runStructuredTask({
    task: "report_writer",
    promptVersion: REPORT_VERSION,
    systemPrompt: REPORT_SYSTEM_PROMPT,
    userMessage: buildReportUserMessage(serializeContext(context)),
    demo: () => demoReport(input),
    schema: reportSchema,
    inputPayload: { report_type: input.reportType, stats: input.stats },
    extractLogFields: (d) => ({ confidence: d.confidence_score, safetyFlags: [] }),
  });
}
